services:

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - .:/app
    env_file:
      - .env
    command: bash -c "bin/rails db:prepare && bin/rails log:clear tmp:clear && bin/rails tailwindcss:build && bin/rails server -b 0.0.0.0 -p 3000"

  database:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME_PREFIX}_development
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
    - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
